## Python Assignment: Data Structures, Functions, Numpy & Pandas

### Assignment Questions
Section A: Data Structures & Control Structures

 1.	Create a list of 5 integers. 
    Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [113]:
my_list = [23,45,93,56,32]  # Creating a List

In [114]:
my_list.append(34)    # Adding a element at last by append()

In [115]:
print(my_list)

[23, 45, 93, 56, 32, 34]

In [116]:
my_list.extend([56,83,20])    # Extending the list

In [117]:
print(my_list)

[23, 45, 93, 56, 32, 34, 56, 83, 20]

In [118]:
my_list.insert(2,46)   # Adding a element at specific index(i.e 2) by insert()

In [119]:
print(my_list)

[23, 45, 46, 93, 56, 32, 34, 56, 83, 20]

In [120]:
my_list.remove(32)   # Remove element 32 from list

In [121]:
print(my_list)

[23, 45, 46, 93, 56, 34, 56, 83, 20]

In [122]:
my_list.pop(3)  # remove element present at index 3

93

In [124]:
print(my_list)

[23, 45, 46, 56, 34, 56, 83, 20]

In [125]:
my_list.index(56)  # return first index of element 56

3

In [127]:
my_list.count(56) # returns occurance of element 56

2

In [129]:
print(my_list)

[23, 45, 46, 56, 34, 56, 83, 20]

In [130]:
my_list.sort()

In [131]:
print(my_list)  # sorting list in Ascending Order

[20, 23, 34, 45, 46, 56, 56, 83]

In [132]:
my_list.reverse()  # reverse the entire list (i.e Also used for arrrange in Descending Order)

In [133]:
print(my_list)

[83, 56, 56, 46, 45, 34, 23, 20]

In [134]:
my_list.clear()  # clear the entire list without any element(i.e Empty list)

In [135]:
print(my_list)

[]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [136]:
my_tuple = ('Abhishek Sharma','Ishan Kishan','Pat Cummins')

In [46]:
print(my_tuple)

('Abhishek Sharma', 'Ishan Kishan', 'Pat Cummins')

In [47]:
tuple[2] = 'Traveis Head'

TypeError: 'tuple' object does not support item assignment

It is giving 'TypeError' , tuple does not support item assignment because 
* Tuples are Mutable, which cannot be changed after creation.
* So, we cannot modify the Tuple

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [48]:
set = {45,56,56,95,23,45,89}

In [49]:
print(set)

{23, 56, 89, 45, 95}

* Set only store unique values in it.
* It doesn't allow Duplicate Values.
* Duplicate elements 56 and 45 are automatically deleted.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [95]:
dict = {'name':'Prabhas','age': 40,'city': 'Hyderabad'}  #creating Dictionary

In [51]:
print(dict)

{'name': 'Prabhas', 'age': 40, 'city': 'Hyderabad'}

In [109]:
dict['age'] = 45  # upadating the age

In [110]:
dict['email'] = 'prabhas0032@gmail.com'  # Adding a key(email)

In [111]:
print(dict)

{'name': 'Prabhas', 'age': 45, 'city': 'Hyderabad', 'email': 'prabhas0032@gmail.com'}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [55]:
age = 32

if age >= 18:
    print('You are eligible to vote')
else:
    print('You are not eligible to vote')

You are eligible to vote

In [97]:
age = int(input('Enter your age'))  # taking input from User

if age >= 18:
    print('You are eligible to vote')
else:
    print('You are not eligible to vote')

Enter your age 34

You are eligible to vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [57]:
marks = 53

if marks >= 90:
    print('A')
elif marks >= 75 and marks <= 89:
    print('B')
elif marks >= 50 and marks <= 74:
    print('C')
else:
    print('Fail')

C

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [58]:
num = 28

if num > 0:
    if num % 2 == 0:
        print("Positive and Even Number")
    else:
        print("Positive but Odd Number")
elif num == 0:
    print("Number is Zero")
else:
    print("Negative Number")

Positive and Even Number

### Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [59]:
import numpy as np

In [60]:
scalar = np.array(5)

In [61]:
scalar

array(5)

In [62]:
scalar.ndim

0

In [63]:
one_d = np.array([1,2,3,4,5])

In [64]:
one_d

array([1, 2, 3, 4, 5])

In [65]:
one_d.ndim

1

In [66]:
two_d = np.array([[10,20,30],[40,50,60]])

In [67]:
two_d

array([[10, 20, 30],
       [40, 50, 60]])

In [68]:
two_d.ndim

2

In [69]:
two_d.shape

(2, 3)

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [70]:
random = np.random.randint(0,100,(4,4))

In [71]:
print(random)

[[32 10  8 81]
 [65 13 77 27]
 [17  0 57 75]
 [24 49 97 34]]

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [72]:
array_2d = np.array([[34,56,23],[45,76,20],[54,89,56]])

In [73]:
array_2d.shape

(3, 3)

In [74]:
import pandas as pd

In [75]:
df = pd.DataFrame(array_2d)

In [76]:
df

    0   1   2
0  34  56  23
1  45  76  20
2  54  89  56

In [77]:
df.columns = ['A','B','C']

In [78]:
df

    A   B   C
0  34  56  23
1  45  76  20
2  54  89  56

### Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [100]:
dataframe = pd.DataFrame([['Abhishek',32,'Hyderabad',120000],
                 ['Head',35,'Nizambad',130000],
                 ['Ishan',30,'Khammam',100000],
                 ['Klassen',40,'Jayithal',125000],
                 ['Reddy',25,'Vizag',100500],
                 ['Abhishek',32,'Hyderabad',120000],
                 ['Ankiet varma',38,'Rangareddy'],
                 ['Pat Cummins',45,'Wrangal',200000],
                 ['Shivang',30,'Suryapet'],
                 ['Klassen',40,'Jayithal',125000]],columns = ['Name','Age','City','Salary'])       # creating a dataframe with 10 rows and 4 columns

In [80]:
print(dataframe)

           Name  Age        City    Salary
0      Abhishek   32   Hyderabad  120000.0
1          Head   35    Nizambad  130000.0
2         Ishan   30     Khammam  100000.0
3       Klassen   40    Jayithal  125000.0
4         Reddy   25       Vizag  100500.0
5      Abhishek   32   Hyderabad  120000.0
6  Ankiet varma   38  Rangareddy       NaN
7   Pat Cummins   45     Wrangal  200000.0
8       Shivang   30    Suryapet       NaN
9       Klassen   40    Jayithal  125000.0

In [81]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [82]:
dataframe.describe()

             Age         Salary
count  10.000000       8.000000
mean   34.700000  127562.500000
std     6.019413   31333.958644
min    25.000000  100000.000000
25%    30.500000  115125.000000
50%    33.500000  122500.000000
75%    39.500000  126250.000000
max    45.000000  200000.000000

In [112]:
print(dataframe[['Name','City']])  # Select the city and name columns

           Name        City
0      Abhishek   Hyderabad
1          Head    Nizambad
2         Ishan     Khammam
3       Klassen    Jayithal
4         Reddy       Vizag
5      Abhishek   Hyderabad
6  Ankiet varma  Rangareddy
7   Pat Cummins     Wrangal
8       Shivang    Suryapet
9       Klassen    Jayithal

In [102]:
df2 = dataframe.drop('City',axis=1)   # Drop city column

In [103]:
print(df2)

           Name  Age    Salary
0      Abhishek   32  120000.0
1          Head   35  130000.0
2         Ishan   30  100000.0
3       Klassen   40  125000.0
4         Reddy   25  100500.0
5      Abhishek   32  120000.0
6  Ankiet varma   38       NaN
7   Pat Cummins   45  200000.0
8       Shivang   30       NaN
9       Klassen   40  125000.0

In [104]:
df2.isnull().sum()  # Finding null values

Name      0
Age       0
Salary    2
dtype: int64

In [87]:
df2['Salary'].mean()

np.float64(127562.5)

In [88]:
df2['Salary'] = df2['Salary'].fillna(df2['Salary'].mean())
print(df2)                #

           Name  Age    Salary
0      Abhishek   32  120000.0
1          Head   35  130000.0
2         Ishan   30  100000.0
3       Klassen   40  125000.0
4         Reddy   25  100500.0
5      Abhishek   32  120000.0
6  Ankiet varma   38  127562.5
7   Pat Cummins   45  200000.0
8       Shivang   30  127562.5
9       Klassen   40  125000.0

In [89]:
df2

           Name  Age    Salary
0      Abhishek   32  120000.0
1          Head   35  130000.0
2         Ishan   30  100000.0
3       Klassen   40  125000.0
4         Reddy   25  100500.0
5      Abhishek   32  120000.0
6  Ankiet varma   38  127562.5
7   Pat Cummins   45  200000.0
8       Shivang   30  127562.5
9       Klassen   40  125000.0

In [90]:
df2 = df2.drop_duplicates()
print(df2)

           Name  Age    Salary
0      Abhishek   32  120000.0
1          Head   35  130000.0
2         Ishan   30  100000.0
3       Klassen   40  125000.0
4         Reddy   25  100500.0
6  Ankiet varma   38  127562.5
7   Pat Cummins   45  200000.0
8       Shivang   30  127562.5

In [94]:
print(df2.reset_index(drop = True))

           Name  Age    Salary
0      Abhishek   32  120000.0
1          Head   35  130000.0
2         Ishan   30  100000.0
3       Klassen   40  125000.0
4         Reddy   25  100500.0
5  Ankiet varma   38  127562.5
6   Pat Cummins   45  200000.0
7       Shivang   30  127562.5